---
- hosts: localhost
  become: true

  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install PHP-FPM
      apt:
        name: php-fpm
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: true

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

